version: '3'

services:

  server:
    command: [ 'pnpm', 'dev' ]
    build:
      dockerfile: ./infra/Dockerfile
      args:
        ENV: development
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - ./apps/backend/:/app/apps/backend
      - ./packages/:/app/packages
    environment:
      - OPENAI_KEY=$OPENAI_KEY
      - DATABASE_URL=$DOCKER_DB_URL
    networks:
      - codechat

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maindb
    ports:
      - 6504:5432
    volumes:
      - ./.postgres-files/:/var/lib/postgresql/data/
    networks:
      - codechat


networks:
  codechat:
    name: codechat

    